Update strapi-custom-api.md to fix some best practices
njfamirm/blog pull request #36
Opened 2023-09-21 13:10 UTC by derrickmehaffy

## Description

Hello from the Strapi team o/

Read through your post and I noticed a few things that could be done a bit better so figured I'd do a PR. Note in my opinion I don't think it's really needed to create a new API but didn't want to completely rewrite the latter half of your article. Generally you could just place the controller + service in the generated factory files for the content-type and create a new route in that same content-type.

That being said you don't actually need to write any code to do what you've described here as you could just do a normal filter for this instead:

`GET /api/reading-list?filters[keyword][$eq]=yourKeyword` 

But I get wanting to get started with Strapi so what you are doing isn't wrong per-say but just wanted to let you know that what you want to do is doable without writing any code :wink:

2023-09-21 13:47 UTC, njfamirm commented
Hi dear friend!
With thanks for your attention
Yes, I will definitely check

2023-09-21 13:52 UTC, njfamirm commented
> `GET /api/reading-list?filters[keyword][$eq]=yourKeyword`

I saw this `filter` but I didn't know how to search in the list of keywords! maybe it's better to save the keywords as a list in db, but I didn't manage to do that.
If I can solve this case, I will switch to the filter

Of course, my goal in this tutorial was to talk about custom API. 
Maybe I need to add another idea to include this goal in the post 😅

2023-09-21 14:57 UTC, derrickmehaffy commented
> > `GET /api/reading-list?filters[keyword][$eq]=yourKeyword`
> 
> I saw this `filter` but I didn't know how to search in the list of keywords! maybe it's better to save the keywords as a list in db, but I didn't manage to do that. If I can solve this case, I will switch to the filter
> 
> Of course, my goal in this tutorial was to talk about custom API. Maybe I need to add another idea to include this goal in the post 😅

Hahaha, indeed there are a lot of use-cases for it. I've done several best practice talks if you want to watch some of them here is our unlisted Youtube Playlist: https://www.youtube.com/playlist?list=PL7Q0DQYATmvg5Ip7hpXypLf_G3-zEWhR6

Typically when I see entirely custom routes + controllers + services being extremely useful is when you are talking to external services but not enough to justify a plugin. Alternatively when you need to condense a response for multiple content-types it can be very useful.

If you are ever on our Discord (https://discord.gg/strapi) we do daily office hours M-F 10:30am to 11:30am PST so you are always welcome to come hang out and chat with us. The Discord is also a really good source of questions and topics if you want to write more blog posts as we can never have enough community members helping share knowledge.

We love to see community members writing articles like this and we even have our own "write for the community" program too :wink:

2023-09-21 17:31 UTC, njfamirm commented
yes, thank you!
Your importance to the community is really admirable! I have rarely seen such a case!

2023-09-21 17:59 UTC, njfamirm commented on site/en/blog/strapi-custom-api.md
> -We must add this endpoint and sets the previous controller as the route handler, put this code to `api/reading-list-search/config/routes.json`:
Wowwwww, what a funny mistake 🤣🤣🤣

2023-09-21 18:02 UTC, njfamirm requested changes

2023-09-21 18:02 UTC, njfamirm commented on site/en/blog/strapi-custom-api.md
> +    return await strapi.entityService.findMany('api::reading-list.reading-list', { filters: { keyword: { $eq: keyword }}});
All items are correct, thank you

Only this line can't search in a list, I divide the keywords based on the new line, can handle it in other way?

2023-09-23 15:39 UTC, njfamirm commented
If you don't have time to continue, tell me so that I can continue

2023-09-26 08:52 UTC, njfamirm approved these changes
I'm continue this

2023-09-26 08:54 UTC, merged

2023-09-26 23:10 UTC, derrickmehaffy commented
Sorry about that! Didn't see your requested changes, there are ways to do multi-filter using the $or operator if you wanted to dive down that path but either way is fine honestly, generally we try to avoid doing filtering in JavaScript since it'll be slower than doing it at the database level.

2023-09-27 11:19 UTC, njfamirm commented
> Sorry about that! Didn't see your requested changes, there are ways to do multi-filter using the $or operator if you wanted to dive down that path but either way is fine honestly, generally we try to avoid doing filtering in JavaScript since it'll be slower than doing it at the database level.

you're welcome
Thank you, I will check